# Generated by Django 3.2.dev20200605191336 on 2020-06-07 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esp32',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esp_id', models.IntegerField(default=0)),
                ('esp_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_temp', models.IntegerField(default=0)),
                ('reading_hum', models.IntegerField(default=0)),
                ('reading_date', models.DateTimeField(verbose_name='Reading date')),
                ('reading_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.esp32')),
            ],
        ),
    ]
